<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder {
    public function run(): void {
        DB::table('users')->insert([
            [
                'name'           => 'Hendri Arifin',
                'phone'          => '085746080544',
                'password'       => Hash::make('12345678'),
                'role'           => 'super_admin',
                'institution_id' => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            // [
            //     'name'           => 'Dwi Lala Santi',
            //     'phone'          => '085732122504',
            //     'password'       => Hash::make('12345678'),
            //     'role'           => 'admin',
            //     'institution_id' => 2,
            //     'created_at'     => now(),
            //     'updated_at'     => now(),
            // ],
            [
                'name'           => 'SELMA ZAHRATU ASYPA',
                'phone'          => '089612879975',
                'password'       => Hash::make('12345678'),
                'role'           => 'user',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'ELISA DEWI YANTI',
                'phone'          => '081248111178',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'AKHMAD SYARKANI',
                'phone'          => '0882022140876',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'ANGGI FEBRIYANI',
                'phone'          => '085845954510',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'SILAWANTY',
                'phone'          => '081256146133',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Sonny Tua Halomoan',
                'phone'          => '081334723977',
                'password'       => Hash::make('12345678'),
                'role'           => 'super_admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Ronald',
                'phone'          => '082254236922',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Rudi Nugraha',
                'phone'          => '082154433558',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Roy',
                'phone'          => '085822038512',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Shadiq',
                'phone'          => '082335383778',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Evi Yusnina',
                'phone'          => '081349468173',
                'password'       => Hash::make('12345678'),
                'role'           => 'super_admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Bella Puspa',
                'phone'          => '081229252560',
                'password'       => Hash::make('12345678'),
                'role'           => 'user',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Nisa Auliah, S. Sos',
                'phone'          => '085349820545',
                'password'       => Hash::make('12345678'),
                'role'           => 'user',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Hj. Rohana, S.S',
                'phone'          => '081373769948',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'name'           => 'Zulham Fathoni, SST.Par',
                'phone'          => '082242755659',
                'password'       => Hash::make('12345678'),
                'role'           => 'admin',
                'institution_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}